### ISSUE TITLE
<AreaOfStudy/> should include a link to the catalog page

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#122]
Probably at the top?

The only problem is that the slugs are weird.

For instance, we’d call “Africa and the Americas” `africa-and-the-americas`, but the catalog has it under [`africa-americas`](http://catalog.stolaf.edu/academic-programs/africa-americas/)

I guess we could add a top-level “slug” key to the file, to tell it where the link should go?

**Comment by hawkrives** [comment]
So the top of the file would then look like

```yaml
name: Sociology/Anthropology
slug: sociology-anthropology
type: major
revision: 2011-12
result: [requirements]
```

And, given that most of the slugs are simply kebab-case’d names, we could even make it an optional key.
