### ISSUE TITLE
Add support for "Pre-professional Programs"

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#2328]
like [Accounting](http://catalog.stolaf.edu/pre-professional-preparation/programs/accounting/) and [Information Technology](http://catalog.stolaf.edu/pre-professional-preparation/programs/office-information-technology/)

They should be fairly simple; something like

```yaml
name: Accounting
type: program(?)
revision: 2018-19
result: Strongly Recommended & Recommended

Strongly Recommended:
  result: all of (MGMT 225, MGMT 237, MGMT 250, MGMT 251, MGMT 252, MGMT 281, MGMT 380)
Recommended:
  note: We also recommend taking courses in statistics and computer science
  studentSelected: true # there's support for something like this; I don't remember the exact naming
```
