### ISSUE TITLE
Add the ability to look up values on the student from HansonFormat files

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#2331]
```yaml
name: English Proofreading
type: emphasis

result: English & Courses

requirements:
    English:
        one major from student where { name = English }
    Courses:
        ENGL 200
```

IE, `one major from student where { name = English }`. Or something.
