### ISSUE TITLE
[tracking] Implement whatever is needed for General Graduation Requirements support

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#2332]
http://catalog.stolaf.edu/curriculum/graduate-requirements-degrees/general-graduation-requirements-ba/

something like this:

```yaml
Courses: 
  result: 35 credits from courses

Residency: 
  result: 17 credits from courses where {institution = STO}

Interim: 
  result: 3 credits from courses where {semester = Interim}

Grade Point Average: 
  result: at least GPA of 2.0 from courses where {graded = yes}

Course Level: 
  result: 18 credits from courses where {level >= 200}

Graded Courses: 
  result: 24 credits from courses where {institution = STO & graded = yes}
  # at most 6 of 35 credits from courses where {su = yes} & # this is another requirement
  # also need to adjust the GE requirements to exclude 1.0/0.5-credit, SU courses

Major: 
  result: >
    1 major from student &
    all majors from student with { {dept_code} => 21 credits from courses where { department != *dept_code } }

result: Courses & Residency & Interim & Grade Point Average & Course Level & Graded Courses & Major
```

this will need:

- [ ] to store the institution on the evaluatable course object (henceforce ECO)
- [ ] to store the grade type on the ECO (graded, pn, su, etc)
- [ ] … and more

---

potential thing I was looking at here: the `with` block, where you can pass a little lambda function to run stuff over $things.

like here:

```
all majors from student with { {dept_code} => 21 credits from courses where { department != *dept_code } }
```

which would … somehow … bind each major to the lambda, then pull out the part of the major requested (`name`, `catalog_year`, `type`, `dept_code`), then run the contents of the block?
