### ISSUE TITLE
Add keywords to courses

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#47]
Initial Proposal: We should define tags on the course data, to help with situations where you cannot easily/at all determine something from the other metadata.

The tags would be defined in a separate file that matches up, like, `crsid` with the set of tags.

**Comment by hawkrives** [comment]
I think we can use the same logic as the registrar does when determining when to change the crsid. That is, if the content changes significantly, the crsid changes.

Otherwise, the content is the same, and the tags don't change.

Unless it's a topics course, in which case each occurence should get its own tags.

**Comment by hawkrives** [comment]
We don't want two departments to pick the same keyword for different things, so we'll also need some way to namespace the keywords.

Colons? Slashes?

**Comment by hawkrives** [comment]
`crossdiscipline:asian-studies` or `crossdiscipline/asian-studies`

**Comment by drewvolz** [comment]
Colons seem to be the best way to go about doing this

**Comment by hawkrives** [comment]
I think I like the colons as well.

We'll need to define the namespaces?

`discipline` should be one, I think. And `topic`?

**Comment by hawkrives** [comment]
Even better: In the English major, when we have the un-denoted pre-1800s/post-1800s split?

We could have some sort of keyword for a time period. `period`?

**Comment by drewvolz** [comment]
Yes, `period works well. That way we can differentiate between certain amounts of time.

**Comment by hawkrives** [comment]
Should we define that on all courses the have some relation to a time period?

**Comment by drewvolz** [comment]
Yes. It will be a good keyword to have as a part of the metadata suggested for the registrar

**Comment by hawkrives** [comment]
They each cover a time period.

I'm thinking that we should probably go ahead and tag them with period, too.

**Comment by drewvolz** [comment]
In addition, we will need more categories.  How about "period", "discipline", and "topic"?

**Comment by hawkrives** [comment]
And maybe just "keyword"? For keywords that aren't mentioned in the title or description?

**Comment by drewvolz** [comment]
Not keyword -- it gets complicated in namespaces. Let departments define their own?

**Comment by hawkrives** [comment]
## New proposal:

These all fall under `keywords`. 

### `counts-toward`
Any areas of study that the course counts toward that wouldn't be immediately obvious. It can be initially populated by any courses that list "Counts towards `xyz`" in their description.


### `sequence`
Defines a sequence of courses. Nothing more, nothing less.

For example, the conversations are a sequence. `AMCON I`, `AMCON II`, `AMCON III`, and `AMCON IV`.


### `topic`
Topics that the course covers. They need to be specific, but not too specific.

### `period`
The time period covered, rounded to a decade.

Not always necessary, but useful to have.

Also supports the `present` keyword.


### `discipline`
Disciplines covered in the course. `asian-studies`, `historical-perspectives`, etc.

Should they be defined solely by the department that's offering the course, or should they require input from the 'target(?)' department, as well?

**Comment by drewvolz** [comment]
counts-toward, sequence, and period look good.  I believe that departments should solely define whether a course counts as interdisciplinary without outside input, but we'll need to check on that one.

**Comment by hawkrives** [comment]
Example, in `yaml` form:

```yaml
CHEM 398:
	discipline: computer science

ENGL 150:
	topic: creative writing
	genre:
		- poetry
		- fiction
		- creative non-fiction

AMCON 101:
	sequence: AMCON I
	period: 1600-1860s
	discipline:
		- writing
		- american studies
		- historical perspectives
	topic:
		- declaration of independence
		- thomas jefferson
		- architecture
		- american civil war
	counts-towards: 
		- amst

AMCON 102:
	sequence: AMCON II
	period: 1800-1900
	discipline:
		- writing
		- american studies
		- historical perspectives
	topic:
		- trancendentalism
		- black elk speaks
		- western photography
	counts-towards: 
		- amst

AMCON 201:
	sequence: AMCON III
	period: 1860s-1940s
	discipline:
		- writing
		- american studies
		- historical perspectives
	topic:
		- statue of liberty
		- columbian exposition
		- ford model t
		- harlem rennaissance
	counts-towards: 
		- amst

AMCON 202:
	sequence: AMCON IV
	period: 1920-present
	discipline:
		- writing
		- american studies
		- historical perspectives
	topic:
		- national parks
		- internment camps
		- poetry
		- freedom summer
		- las vegas
		- mall of america
	counts-towards: 
		- amst
		- m-wmgst
		- c-wmgst
```
